---
- name: Define he_host_ip
  block:
  - name: Define host ip if management bridge is not defined
    shell: ip addr | grep {{ he_bridge_if }} | grep 'inet ' | cut -d' ' -f6 | cut -d'/' -f1
    changed_when: true
    register: host_ip_no_bridge
  - debug: var=host_ip_no_bridge
  - name: Define host ip if management bridge is defined
    shell: ip addr | grep {{ he_mgmt_network }} | grep 'inet ' | cut -d' ' -f6 | cut -d'/' -f1
    changed_when: true
    register: host_ip_bridge
    when: not host_ip_no_bridge.stdout
  - debug: var=host_ip_bridge
  - name: Set he_host_ip
    set_fact:
      he_host_ip: "{{ host_ip_bridge.stdout if host_ip_bridge.stdout is defined else host_ip_no_bridge.stdout }}"
    register: he_host_ip
  - debug: var=he_host_ip

- name: Fail if host's ip is empty
  fail:
    msg: Host has no IP address
  when: not he_host_ip
