---
- name: Install ovirt-engine-appliance rpm
  yum:
    name: ovirt-engine-appliance
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
- name: Parse appliance configuration for path
  shell: grep path /etc/ovirt-hosted-engine/10-appliance.conf | cut -f2 -d'='
  environment: "{{ he_cmd_lang }}"
  register: he_appliance_ova_out
  changed_when: true
- debug: var=he_appliance_ova_out
- name: Parse appliance configuration for sha1sum
  shell: grep sha1sum /etc/ovirt-hosted-engine/10-appliance.conf | cut -f2 -d'='
  environment: "{{ he_cmd_lang }}"
  register: he_appliance_ova_sha1
  changed_when: true
- debug: var=he_appliance_ova_sha1
- name: Get OVA path
  set_fact:
    he_appliance_ova_path: "{{ he_appliance_ova_out.stdout_lines|first }}"
    cacheable: true
- debug: var=he_appliance_ova_path
- name: Compute sha1sum
  stat:
    path: "{{ he_appliance_ova_path }}"
    checksum_algorithm: sha1
  register: ova_stats
- debug: var=ova_stats
- name: Compare sha1sum
  fail:
    msg: "{{ he_appliance_ova_path }} is corrupted (sha1sum)"
  when: he_appliance_ova_sha1.stdout_lines|first != ova_stats.stat.checksum
